language: java
dist: bionic
jdk: openjdk11
script:
  - sudo mkdir /floodgate
  - sudo chmod 777 /floodgate
  - mkdir /floodgate/bin
  - SWAGGER_VERSION=$(cat gateapi/.swagger-codegen/VERSION)
  - wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/${SWAGGER_VERSION}/swagger-codegen-cli-${SWAGGER_VERSION}.jar -O swagger-codegen-cli.jar
  - wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/${SWAGGER_VERSION}/swagger-codegen-cli-${SWAGGER_VERSION}.jar.sha1 -O swagger-codegen-cli.jar.sha1
  - echo ' swagger-codegen-cli.jar' >> swagger-codegen-cli.jar.sha1
  - sha1sum -c swagger-codegen-cli.jar.sha1
  - git clone https://github.com/spinnaker/gate.git -b << parameters.gate_api_branch >> /floodgate/gate
  - cd /floodgate/gate && ./gradlew clean && ./gradlew gate-web:test --tests *GenerateSwagger* --max-workers 2 && cat gate-web/swagger.json | json_pp > ./gate-swagger.json
  - java -jar /floodgate/bin/swagger-codegen-cli.jar generate -l go -i /floodgate/gate/gate-swagger.json -o /floodgate/gateapi
